name: shallow2deep

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pytorch=1.10.2
  - torchvision
  - tensorboard
  - h5py
  - scipy
  - scikit-image
  - scikit-learn
  - pyyaml
  - pytest
  - matplotlib
  - setuptools=59.5.0  # this fixes incompatibilities
  - python-elf
